##  Ajout de la cible Soil_Moisture_J1

Dans ce notebook, nous ajoutons une nouvelle colonne appelée `Soil_Moisture_J1`.

Cette colonne représente une estimation de l'humidité du sol au jour suivant.

In [1]:
import pandas as pd 
import numpy as np

In [2]:

df = pd.read_csv(r"C:\Users\kerro\OneDrive\Bureau\smart_agri2\data\irrigation_prediction_11cols.csv")
df.head()

,Soil_Type,Soil_pH,Soil_Moisture,Temperature_C,Humidity,Rainfall_mm,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Mulching_Used,Region
0,Clay,6.14,36.48,21.90,31.19,1167.70,1.97,Wheat,Vegetative,Yes,South
1,Silt,6.41,50.56,36.50,26.01,831.28,16.82,Maize,Flowering,Yes,Central
2,Sandy,7.71,40.07,41.83,76.41,1844.45,19.03,Cotton,Harvest,Yes,South
3,Clay,5.96,12.75,37.22,43.32,306.26,11.44,Wheat,Sowing,Yes,North
4,Clay,7.76,18.58,22.38,86.44,1875.63,11.26,Cotton,Sowing,No,South

In [3]:
df["Soil_Moisture_J1"] = (
    df["Soil_Moisture"]
    + 0.015 * df["Rainfall_mm"]
    + 0.05 * df["Humidity"]
    - 0.30 * df["Temperature_C"]
    - 0.40 * df["Wind_Speed_kmh"]
)

df["Soil_Moisture_J1"] = df["Soil_Moisture_J1"].clip(0, 100)

In [4]:
df[[ "Soil_Moisture","Soil_Moisture_J1"]].head(15)

    Soil_Moisture  Soil_Moisture_J1
0           36.48          48.19700
1           50.56          46.65170
2           40.07          51.39625
3           12.75           3.76790
4           18.58          39.81845
5           20.50          14.24730
6           22.70          25.74125
7           40.23          44.51295
8           36.73          72.01745
9           19.58          28.99925
10          11.85          29.64185
11          17.77          25.58660
12          64.11          90.40585
13          34.71          35.10775
14          57.44          72.88685

In [5]:
df.to_csv("../data/irrigation_prediction_12cols.csv", index=False)